### ISSUE TITLE
Getting OOM killed when I enable swagger autogen function

### ISSUE THREAD

**Issue by tbhaxor** [swagger-autogen/swagger-autogen#220]
I am getting this error

There total 134 files
```js
await swaggerAutogen()(outputFile, endpointsFiles, swaggerDoc).then(() => {
	logger.info(`Swagger generation completed in ${outputFile}`);
});
```
![image](https://github.com/swagger-autogen/swagger-autogen/assets/28386721/79f8dee5-84bc-40d6-a5c3-ba1b09000cef)

**Comment by tbhaxor** [comment]
I just checked, with `endpointsFiles.slice(0, 100)` it works fine. But when I increase the files to `endpointsFiles.slice(0, 105)` I get that error.

**Comment by tbhaxor** [comment]
It was tsconfig issue. Using es2022 target solved it.

**Comment by davibaltar** [comment]
Hi @tbhaxor. Thank you for reporting this. It'll be good to have this answer here because some people could have the same problem. Thanks!
