### ISSUE TITLE
Define array of items as response type

### ISSUE THREAD

**Issue by Yoann-TYT** [swagger-autogen/swagger-autogen#223]
In swagger, this definition....

```json
"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/UserRead"
              }
            }
          },
```

... return this result 

<img width="230" alt="Capture d’écran 2023-09-06 à 17 59 02" src="https://github.com/swagger-autogen/swagger-autogen/assets/9287634/ae8fe839-b3b1-45e1-8a0e-985a6981a19f">

But, when I define this rule 

```js
#swagger.responses[200] = { schema: { type: 'array', items: { $ref: "#/definitions/UserRead" } } }
```

The result does not meet my expectations

```json
"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "array"
                },
                "items": {
                  "$ref": "#/definitions/UserRead"
                }
              },
```

<img width="187" alt="Capture d’écran 2023-09-06 à 18 04 32" src="https://github.com/swagger-autogen/swagger-autogen/assets/9287634/511df5d3-48c1-4188-9dea-9937f2169bba">

Thanks a lot :)

**Comment by davibaltar** [comment]
Hi @Yoann-TYT. In this case you could use the keyword ['@schema'](https://swagger-autogen.github.io/docs/swagger-2/schemas-and-definitions#schema). Using it, the lib will ignore the render and put your schema content exactly how you define. So you could do:

```js
// #swagger.responses[200] = { '@schema': { type: 'array', items: { $ref: "#/definitions/UserRead" } } }
```

Let me know if it doesn't work.

**Comment by Yoann-TYT** [comment]
Hi @davibaltar !

Thanks a lot for this tips ;)
It works successfully ! 

<img width="232" alt="Capture d’écran 2023-09-12 à 08 44 57" src="https://github.com/swagger-autogen/swagger-autogen/assets/9287634/16ef45a5-b1f6-4d0b-9238-3aedb6f218bf">
