### ISSUE TITLE
Same endpoint with different methods doesn't show all documentation

### ISSUE THREAD

**Issue by tbhaxor** [swagger-autogen/swagger-autogen#225]
So I have two endpoints `GET /events` and `POST /events`, it only shows the documentation of `POST /events`. I have confirmed with curl request that `GET /events` is also registered, but somehow swagger-autogen is overriding the method name and document of routes.

**Comment by davibaltar** [comment]
Hi @tbhaxor. Thank you for opening the issue. Do you have any sample project that reproduces this problem? That way is easier to identify and handle the problem.

**Comment by tbhaxor** [comment]
Please do not close it if inactive. It could take some more time.

**Comment by tbhaxor** [comment]
@davibaltar Here you go https://github.com/tbhaxor/swagger-autogen-bug

```
npm ci
node index.js
```

You can see the build file `swagger.json`. Also I wrote problem statement [here](https://github.com/tbhaxor/swagger-autogen-bug/blob/main/index.js#L23-L28) for your reference.

**Comment by davibaltar** [comment]
Thank you so much for the sample @tbhaxor. 

I'll fork it and any news about this fix, I'll post it here. Thnks!

**Comment by tbhaxor** [comment]
Hi @davibaltar did you get time to check this one?

**Comment by davibaltar** [comment]
Hi @tbhaxor. I've just fixed it. If the problem persists, let me know, please.

Version with that fix: v2.23.6

**Comment by tbhaxor** [comment]
Yeah it worked now. Thanks
