### ISSUE TITLE
Cannot properly utilize oneOf

### ISSUE THREAD

**Issue by aorlowskiddm** [swagger-autogen/swagger-autogen#243]
Hi, all.

According to previous issues, for OpenAPI 3.0, `anyOf` and `oneOf` are not supported in the `@definitions`.  

**If they were supported in `@definitions`**, I would have something like this:

```
    BaseCondition: {
      type: "object",
      properties: {
        jsonPath: { type: "string" },
        conditionalOn: { type: "object" } 
      },
      required: ["jsonPath", "conditionalOn"]
    },
    CompositeCondition: {
      type: "object",
      properties: {
        type: { type: 'string', enum: ['AND', 'OR']},
        conditions: {
          type: 'array', 
          items: {
            oneOf: [
              {$ref: '#/components/schemas/BaseCondition'},
              {$ref: '#/components/schemas/CompositeCondition'}
            ]
          }
        }
      },
      required: ['type', 'conditions']
    },
```

But because `oneOf` is not supported there, I need to put it in the components/schema. However, since swagger-autogen is using its own format in that section (for example, required keys are prepended with `$`), I cannot put it there.)

I am sure that I am doing something wrong here. This seems like a pretty simple case. Please let me know any doc which can point me in the right direction.

**Comment by davibaltar** [comment]
Hi @aorlowskiddm! Thank you for opening the issue. 

As you are using `components/schemas`, you could use `@schema` to put the OpenAPI specification by yourself, that is, that way our lib won't do rederization. Take a look at [schemas-and-components#schemas](https://swagger-autogen.github.io/docs/openapi-3/schemas-and-components#schemas). There will be an example about it.

Let me know if it doesn't work in your case.

**Comment by aorlowskiddm** [comment]
@davibaltar Thank you for the prompt reply. 

I added the schema to the `@schemas` per your directive, but the Swagger page is rendering it incorrectly.

```
components: {
    schemas: {
       RuleMappingCreateContext: {
          condition: { $ref: '#/components/schemas/Condition' },
        },
    },
    '@schemas': {
      CompositeCondition: {
        type: "object",
        properties: {
          type: { type: 'string', enum: ['AND', 'OR']},
          conditions: {
            type: 'array', 
            items: {
              oneOf: [
                {$ref: '#/components/schemas/BaseCondition'},
                {$ref: '#/components/schemas/CompositeCondition'}
              ]
            }
          }
        },
        required: ['type', 'conditions']
      }
    },
    Condition: {
        oneOf: [
          {$ref: '#/components/schemas/BaseCondition'},
          {$ref: '#/components/schemas/CompositeCondition'}
        ]
      }
  },
 ```

It is not showing anything for it at all in Swagger for `RuleMappingCreateContext`:

<img width="213" alt="image" src="https://github.com/swagger-autogen/swagger-autogen/assets/116679946/d76b05cd-4cdb-4b59-8904-f266f12f95b4">

**Comment by aorlowskiddm** [comment]
Just to test it out, if I change the `condition` of the `RuleMappingCreateContext` to `#/components/schemas/CompositeCondition` instead, everything renders correctly on Swagger's end _except_ for the `oneOf` part of the schema. It simply shows an empty list :

<img width="219" alt="image" src="https://github.com/swagger-autogen/swagger-autogen/assets/116679946/9ea26181-631d-46f0-b940-0b19eca4502a">

**Comment by aorlowskiddm** [comment]
If it helps, I am instantiating `swagger-autogen` in this way:

```
const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})
```

**Comment by aorlowskiddm** [comment]
After closing the laptop for a bit, I've come to realize that there's a 99% certainty that this issue is being caused by the package I am using to serve Swagger, (`swagger-ui-koa`), and nothing to do with `swagger-autogen`.

**Comment by aorlowskiddm** [comment]
Yes, I was correct. I replaced `swagger-ui-koa` with `koa2-swagger-ui` and it is rendering identically to the Swagger editor now.  

Thanks @davibaltar for your comment which gave me confidence that I was correctly inputting to `swagger-autogen`.

**Comment by davibaltar** [comment]
No worries @aorlowskiddm. And it's good to know! anyone who might be facing the same problem, your comments will help them. Thanks!
